### ISSUE TITLE
Publish to the Chrome Store

### ISSUE THREAD

**Issue by Tanner-Scadden** [CodeClimbersIO/browser-extension#11]
Dependent on us getting #6 done.

**Comment by Tanner-Scadden** [comment]
This is all done once https://github.com/CodeClimbersIO/cli/pull/86 is merged!

**Comment by Tanner-Scadden** [comment]
Fix for the host issue is in here:
https://github.com/CodeClimbersIO/browser-extension/pull/23

**Comment by rphovley** [comment]
published to chrome store
