### ISSUE TITLE
Set up way to publish to chrome store through github actions

### ISSUE THREAD

**Issue by Tanner-Scadden** [CodeClimbersIO/browser-extension#25]

**Comment by programmerraja** [comment]
Can i work on this?

**Comment by rphovley** [comment]
@programmerraja yes! That'd be great

**Comment by programmerraja** [comment]
@rphovley  Does the repo registered under hacktofest?

**Comment by rphovley** [comment]
@programmerraja I wish I had remembered about Hacktoberfest. We aren't part of it but definitely should do that next year.

**Comment by programmerraja** [comment]
@rphovley can you check this #41  can you kindly review it

**Comment by rphovley** [comment]
HI @programmerraja after merging it, I did some looking at how to generate the client_id and client_secret, and I'm not confident it's a process that's fully automated. 

Looks like the github action makes use of an npm library called chrome-webstore-upload. The directions they give for getting your client_id and client_secret are here: https://github.com/fregante/chrome-webstore-upload-keys

Looks like the suggested method for this is to use OAuth tokens that will require manually refreshing by me through the terminal. 

I'd prefer to have a method that the keys have a longer lifetime than what I think those Oauth tokens have which I'd think is at most a couple weeks. Thoughts?

**Comment by programmerraja** [comment]
@rphovley I will do some research from my side and let you know how we can move further

**Comment by programmerraja** [comment]
@rphovley if you check this https://developer.chrome.com/docs/webstore/using-api where google is suggesting to use access token and refresh token. i think when the access token expired the chrome-extension-upload will use the refresh token and get the new acess token so it will work for couple weeks. we will know only if we try this.

 what you think do you have concern regarding our current approach

some other resources
- https://jam.dev/blog/automating-chrome-extension-publishing/

**Comment by rphovley** [comment]
@programmerraja I missed seeing the refresh token in the PR. I think this should work great. Thanks for diving into this! Much appreciated

**Comment by programmerraja** [comment]
@rphovley Cool. but it checked PR #42 where you removed this is there is any reason for it ? did i make any mistake ?

**Comment by rphovley** [comment]
@programmerraja I had merged it and then realized that it potentially wouldn't work and reverted the PR which is when I sent you the message about the refresh token. 

You'll need to create a new PR and I can merge in you work

**Comment by programmerraja** [comment]
@rphovley kindly can you check the #43 PR

**Comment by rphovley** [comment]
Merged, thank you for your hard work!
