### ISSUE TITLE
CLI: Sentry Error on Pulse Entry

### ISSUE THREAD

**Issue by Tanner-Scadden** [CodeClimbersIO/browser-extension#31]
Got these alerts from Sentry. Not very useful information on the free tier though.

Was able to reproduce it locally by switching tabs fast. The hash isn't unique at that point. If this is intentional, we should handle the error more gracefully and not send back a 500. 

https://codeclimbers.sentry.io/share/issue/bab324cee7394cc0b77b14489e3da943/
https://codeclimbers.sentry.io/share/issue/c0583e646e5e4311b150f810dac8ed0b/

**Comment by rphovley** [comment]
Great to handle this on the browser extension side, we should also handle more gracefully on the server side

**Comment by Tanner-Scadden** [comment]
@rphovley Will spin this off in the CLI repo too!
