### ISSUE TITLE
Test: Write some test around functionality we are keeping 

### ISSUE THREAD

**Issue by Tanner-Scadden** [CodeClimbersIO/browser-extension#5]
- White List check
- Black List check
- Tests around store being updated
- Tests for the utils (Remove what isn't needed)

Remove the snapshot tests maybe?

**Comment by Tanner-Scadden** [comment]
Removed the snapshot tests. I think testing with Playwright would be best if it supports browser plugins?

**Comment by rphovley** [comment]
Tbh, I'd prefer not to test components at the moment until we get a bit farther along. I think jest unit tests would be great for testing the utils and anything else that we can test without having to create mocks
